# Generated by Django 3.2.8 on 2021-10-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-group'], 'verbose_name': 'аккаунт', 'verbose_name_plural': 'аккаунты'},
        ),
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.IntegerField(verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.CharField(max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
    ]
