# Generated by Django 3.2.8 on 2021-11-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211020_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.RemoveField(
            model_name='account',
            name='group',
        ),
        migrations.RemoveField(
            model_name='account',
            name='login',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
