# Generated by Django 3.2.8 on 2021-11-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211125_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='summ',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
