# Generated by Django 3.2.8 on 2021-11-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=128)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_kit', models.CharField(max_length=128)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
