# Generated by Django 3.2.8 on 2021-10-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название команды')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlayersMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_materials', models.CharField(max_length=100)),
                ('count_materials', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='player.players')),
            ],
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
    ]
