# Generated by Django 3.2.8 on 2021-10-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_players_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyactions',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='player.players'),
        ),
    ]
